version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /home/node/app/.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    